var interVal = setInterval(function(){ 
var $test = $('pre').html();
$test = $test.replace(/\[Intro]/gi, '<span class="kuning">Intro</span></p>');
$test = $test.replace(/\[Chorus]/gi, '<span class="kuning">Chorus</span></p>');
$test = $test.replace(/\[Int]/gi, '<span class="kuning">Int</span></p>');
$test = $test.replace(/\[Musik]/gi, '<span class="kuning">Musik</span></p>');
$test = $test.replace(/\[Music]/gi, '<span class="kuning">Music</span></p>');
$test = $test.replace(/\[Verse]/gi, '<span class="kuning">Verse</span></p>');
$test = $test.replace(/\[Reff]/gi, '<span class="kuning">Reff</span></p>');
$test = $test.replace(/\[Outro]/gi, '<span class="kuning">Outro</span></p>');
$test = $test.replace(/\[Overtune]/gi, '<span class="kuning">Overtune</span></p>');
$test = $test.replace(/\[reff]/gi, '<span class="kuning">Reff</span></p>');
$test = $test.replace(/\[Bridge]/gi, '<span class="kuning">Bridge</span></p>');
$test = $test.replace(/\[Interlude]/gi, '<span class="kuning">Interlude</span></p>');
$test = $test.replace(/\[Instrumental]/gi, '<span class="kuning">Instrumental</span></p>');
$test = $test.replace(/\[Verse 1]/gi, '<span class="kuning">Verse 1</span></p>');
$test = $test.replace(/\[Verse 2]/gi, '<span class="kuning">Verse 2</span></p>');
$test = $test.replace(/\[Verse 3]/gi, '<span class="kuning">Verse 3</span></p>');
$test = $test.replace(/\[Verse 4]/gi, '<span class="kuning">Verse 4</span></p>');
$test = $test.replace(/\[Reff 1]/gi, '<span class="kuning">Reff 1</span></p>');
$test = $test.replace(/\[Reff 2]/gi, '<span class="kuning">Reff 2</span></p>');
$test = $test.replace(/\[Reff 3]/gi, '<span class="kuning">Reff 3</span></p>');
$test = $test.replace(/\[Reff 4]/gi, '<span class="kuning">Reff 4</span></p>');
$test = $test.replace(/\[Intro Chorus]/gi, '<span class="kuning">Intro Chorus</span></p>');
$test = $test.replace(/\[Pre-Chorus 1]/gi, '<span class="kuning">Pre-Chorus 1</span></p>');
$test = $test.replace(/\[Pre-Chorus 2]/gi, '<span class="kuning">Pre-Chorus 2</span></p>');
$test = $test.replace(/\[Pre-Chorus 3]/gi, '<span class="kuning">Pre-Chorus 3</span></p>');
$test = $test.replace(/\[Post-Chorus 1]/gi, '<span class="kuning">Post-Chorus 1</span></p>');
$test = $test.replace(/\[Post-Chorus 2]/gi, '<span class="kuning">Post-Chorus 2</span></p>');
$test = $test.replace(/\[Post-Chorus 3]/gi, '<span class="kuning">Post-Chorus 3</span></p>');
$test = $test.replace(/\[Chorus 1]/gi, '<span class="kuning">Chorus 1</span></p>');
$test = $test.replace(/\[Chorus 2]/gi, '<span class="kuning">Chorus 2</span></p>');
$test = $test.replace(/\[Chorus 3]/gi, '<span class="kuning">Chorus 3</span></p>');
$test = $test.replace(/\[Bridge 1]/gi, '<span class="kuning">Bridge 3</span></p>');
$test = $test.replace(/\[Bridge 2]/gi, '<span class="kuning">Bridge 3</span></p>');
$test = $test.replace(/\[Bridge 3]/gi, '<span class="kuning">Bridge 3</span></p>');
$test = $test.replace(/\[Post-Chorus]/gi, '<span class="kuning">Post-Chorus</span></p>');
$test = $test.replace(/\[Pre-Chorus]/gi, '<span class="kuning">Pre-Chorus</span></p>');
$test = $test.replace(/\[Chorus I]/gi, '<span class="kuning">Chorus I</span></p>');
$test = $test.replace(/\[Chorus II]/gi, '<span class="kuning">Chorus II</span></p>');
$test = $test.replace(/\[Chorus III]/gi, '<span class="kuning">Chorus III</span></p>');
$test = $test.replace(/\[Verse I]/gi, '<span class="kuning">Verse I</span></p>');
$test = $test.replace(/\[Verse II]/gi, '<span class="kuning">Verse II</span></p>');
$test = $test.replace(/\[Verse III]/gi, '<span class="kuning">Verse III</span></p>');
$test = $test.replace(/\[Verse IIII]/gi, '<span class="kuning">Verse IIII</span></p>');
$test = $test.replace(/\[Melodi]/gi, '<span class="kuning">Melodi</span></p>');
$test = $test.replace(/\[Tab]/gi, '<span class="kuning">Tab</span></p>');
$test = $test.replace(/\[Duet]/gi, '<span class="kuning">Duet</span></p>');
$test = $test.replace(/\[Intro 2]/gi, '<span class="kuning">Intro 2</span></p>');
$test = $test.replace(/\[Ending]/gi, '<span class="kuning">Ending</span></p>');
$test = $test.replace(/Capo fret 1/gi, '<span class="kuning">Capo fret 1</span></p>');
$test = $test.replace(/Capo fret 2/gi, '<span class="kuning">Capo fret 2</span></p>');
$test = $test.replace(/Capo fret 3/gi, '<span class="kuning">Capo fret 3</span></p>');
$test = $test.replace(/Capo fret 4/gi, '<span class="kuning">Capo fret 4</span></p>');
$test = $test.replace(/Capo fret 5/gi, '<span class="kuning">Capo fret 5</span></p>');
$test = $test.replace(/Capo fret 6/gi, '<span class="kuning">Capo fret 6</span></p>');
$test = $test.replace(/Capo fret 7/gi, '<span class="kuning">Capo fret 7</span></p>');
$test = $test.replace(/Capo fret 8/gi, '<span class="kuning">Capo fret 8</span></p>');
$test = $test.replace(/\[Drop]/gi, '<span class="kuning">Drop</span></p>');
$('pre').html($test);
}, 3000);
 setTimeout(function (argument) {
    clearInterval(interVal);
 }, 5000);
